### ISSUE TITLE
WCS Penguin 1.22.0 release task list

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1697]
[Master Thread](https://wcship.wordpress.com/2019/08/07/woocommerce-services-1-22-0-master-thread/)

- [x] Ensure that all issues in the [milestone](https://github.com/Automattic/woocommerce-services/milestone/36) have been closed
- [x] Ensure all changelog entries are entered and follow the [Extendables format](https://extendomattic.wordpress.com/standardizations/) (https://github.com/Automattic/woocommerce-services/issues/1697)
- [ ] Work with @californiakat on any doc changes that need to take place
- [x] Remove USPS logo from rates if we have not received permission to use (handled in #1750)
- [x] Complete https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ

**Comment by laurendavissmith** [comment]
@c-shultz I've assigned you since you're up for release lead
