### ISSUE TITLE
Editable Packing Solution in the Labels UI

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#572]
This is an epic. The Labels UI should support
- [x] moving items between packages in the packing solution
- [x] displaying an editable weight for each package based on the package and the items in it
- [x] adding a shared (custom) package to the packing solution
- [x] removing packages from the packing solution
- [x] adding a flat rate package to the packing solution
- [ ] requesting a packing solution when none is available from checkout
- [ ] warning the merchant if the combined weight of the items exceeds a package limit
- [ ] warning the merchant if the item(s) will not fit in a given package

**Comment by laurendavissmith** [comment]
Closing, it looks like this was mostly completed so we'll wait and see on the other items
